name: httomolib
channels:
  - conda-forge
  - anaconda
  - httomo
dependencies:
  - conda-forge::numpy<=1.23
  - conda-forge::scipy
  - conda-forge::python
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::pytest-cov
  - conda-forge::flake8
  - conda-forge::pyproject-flake8
  - conda-forge::pydocstyle
  - conda-forge::imageio
  - conda-forge::toml
  - conda-forge::setuptools-git-versioning
  - anaconda::ipython
  - httomo::larix
